name: Auto-update package

on: [push]

jobs:
  run-package-script:
    env:
      LEVEL_ACCESS_NPM_TOKEN: ${{ secrets.LEVEL_ACCESS_NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies

        run: npm install

      - name: Run package script
        run: npm run package

      - name: Commit, tag and push changes
        run: |
          VERSION=$(node -p "require('./package.json').version")
          sh ci-scripts/commit-and-tag.sh "$VERSION" "${{ github.ref }}"
